export type Project = {
  slug: string;
  title: string;
  kicker: string;
  status: string;
  description: string;
  why: string;
  built: string;
  hardPart: string;
  result: string;
  repo: string;
  tech: string[];
  architecture: string[];
  accent: string;
  media?: { type: 'image' | 'video'; src: string; alt: string };
};

export const projects: Project[] = [
  {
    slug: 'golazo',
    title: 'Golazo',
    kicker: 'Real-time systems · Mobile · Solana',
    status: 'Working product prototype',
    description: 'A live event-market engine built for the seconds when a match changes.',
    why: 'Sports markets become most interesting at the exact moment the underlying event moves. Golazo tests what a product looks like when detection, pricing, participation, and payout all happen in that window.',
    built: 'A React Native client, AI-assisted feed watcher, tested parimutuel core, live market state, and Solana settlement flow.',
    hardPart: 'Keeping event detection, market state, pricing, and settlement coherent while the game keeps moving.',
    result: 'An end-to-end product with a real mobile interface, payout flow, tests, and launch media.',
    repo: 'https://github.com/RealWooblay/golazo',
    tech: ['TypeScript', 'React Native', 'Fastify', 'Solana', 'AI event detection'],
    architecture: ['LIVE FEED', 'EVENT WATCHER', 'MARKET ENGINE', 'MOBILE CLIENT', 'SETTLEMENT'],
    accent: '#d66e22',
    media: { type: 'video', src: '/media/golazo/golazo_hero_vertical.mp4', alt: 'Golazo live market product capture' },
  },
  {
    slug: 'wooblay-ai',
    title: 'Wooblay AI',
    kicker: 'Agent security · Policy · Infrastructure',
    status: 'Active system',
    description: 'An execution firewall between autonomous agents and the systems they can change.',
    why: 'Agents become useful when they can act. That same step creates the real engineering problem: permissions, credentials, approval, and proof of what happened.',
    built: 'Policy gates, isolated credentials, explicit human approval, controlled execution, and tamper-evident receipts.',
    hardPart: 'Making the secure path the normal path without reducing the agent to a read-only demo.',
    result: 'A concrete control plane for agent actions rather than another conversational wrapper.',
    repo: 'https://github.com/RealWooblay/WooblayAI',
    tech: ['TypeScript', 'Policy engine', 'Credential isolation', 'Audit receipts'],
    architecture: ['AGENT INTENT', 'POLICY GATE', 'HUMAN APPROVAL', 'ISOLATED EXECUTION', 'RECEIPT'],
    accent: '#d9ff43',
  },
  {
    slug: 'bubble-wars',
    title: 'Bubble Wars',
    kicker: 'Hackathon winner · Telegram · On-chain game',
    status: 'ETHGlobal Bangkok winner',
    description: 'A collaborative strategy game that turns verified Telegram communities into on-chain factions.',
    why: 'Most on-chain games begin with wallets and mechanics. Bubble Wars began with an existing social graph and made identity, collaboration, raids, and state part of one playable loop.',
    built: 'Verified user identity, referral and faction mechanics, randomised raids, indexed contract state, and a trusted AI runtime inside a Telegram-native flow.',
    hardPart: 'Coordinating social identity, probabilistic game logic, cross-service state, and on-chain settlement inside a hackathon clock.',
    result: 'A working project, an ETHGlobal Bangkok prize, and a live stage presentation.',
    repo: 'https://github.com/RealWooblay/bubblewars',
    tech: ['TypeScript', 'Telegram', 'Solidity', 'Chainlink', 'AI runtime'],
    architecture: ['TELEGRAM', 'VERIFIED PLAYER', 'GAME ENGINE', 'INDEXED STATE', 'CONTRACTS'],
    accent: '#ff3c69',
    media: { type: 'image', src: '/media/bubblewars/banner.png', alt: 'Bubble Wars project banner' },
  },
  {
    slug: 'meridian',
    title: 'MERIDIAN',
    kicker: 'Hackathon winner · Genomics · Governed AI',
    status: 'Hackathon winner',
    description: 'A privacy-first pharmacogenomics system designed to keep medical AI inside explicit evidence and governance boundaries.',
    why: 'Genomic guidance is a bad place for unconstrained generation. MERIDIAN asks how useful AI can remain when provenance, privacy, and clinical boundaries are first-class system requirements.',
    built: 'A governed genome-processing flow, evidence-bound guidance, constrained medical AI, and an interface that exposes sources instead of hiding them.',
    hardPart: 'Turning sensitive biological input into useful guidance without allowing the model to invent clinical certainty.',
    result: 'A complete hackathon system and winning project with an architecture that treats safety as product behavior.',
    repo: 'https://github.com/RealWooblay/medhack',
    tech: ['TypeScript', 'Python', 'Genomics', 'Retrieval', 'Guardrailed AI'],
    architecture: ['GENOME INPUT', 'GOVERNED PROCESSING', 'EVIDENCE RETRIEVAL', 'CONSTRAINED MODEL', 'GUIDANCE'],
    accent: '#78a8ff',
  },
  {
    slug: 'wisp-lab',
    title: 'WISP Lab',
    kicker: 'Jetson · Perception · Spatial computing',
    status: 'Current physical-systems build',
    description: 'An embedded spatial computer that uses perception, projection, and interaction to put useful software onto physical surfaces.',
    why: 'A screen is not the only place software can live. WISP explores a local device that can understand a room, choose a surface, project an interface, and correct itself through camera feedback.',
    built: 'A Jetson perception service, head-tracked renderer, hand interaction, planner boundary, and four-corner projection calibration.',
    hardPart: 'Keeping perception latency, head geometry, interaction state, and projector alignment honest enough to survive outside a screen demo.',
    result: 'YOLOv8n detection at 31.6 FPS with TensorRT FP16, a working head/hand state stream, and a renderer ready for physical projector calibration.',
    repo: 'https://github.com/RealWooblay/wisp-lab',
    tech: ['NVIDIA Jetson', 'Python', 'TensorRT', 'YOLO', 'SSE', 'Projection mapping'],
    architecture: ['IMX708 CAMERA', 'TENSORRT POSE', 'STATE STREAM', 'PLANNER', 'PROJECTED SURFACE'],
    accent: '#efb65d',
    media: { type: 'image', src: '/media/wisp/wisp-hero-real.png', alt: 'WISP spatial computing device concept' },
  },
  {
    slug: 'bender',
    title: 'Bender',
    kicker: 'Unity 6 · Multiplayer · Dedicated sessions',
    status: 'Game systems prototype',
    description: 'A Unity multiplayer prototype exploring lobby matchmaking and live handoff into dedicated game sessions.',
    why: 'Multiplayer architecture becomes real when a lobby must allocate a session, start it, and move connected clients without hiding the lifecycle.',
    built: 'A FishNet lobby flow, headless dedicated session process, dynamic port allocation, session lifecycle, and TargetRpc client handoff.',
    hardPart: 'Coordinating process lifecycle and network handoff while keeping the client transition understandable.',
    result: 'A focused game-networking prototype that makes dedicated session orchestration concrete.',
    repo: 'https://github.com/RealWooblay/bender',
    tech: ['Unity 6', 'C#', 'FishNet', 'Dedicated servers'],
    architecture: ['UNITY CLIENT', 'LOBBY :7777', 'SESSION MANAGER', 'DYNAMIC PORT', 'GAME SESSION'],
    accent: '#b38cff',
  },
  {
    slug: 'minitown-ai',
    title: 'MiniTown AI',
    kicker: 'Unity · Agent world model · AI NPCs',
    status: 'Two-repository prototype',
    description: 'A small Unity world whose lore, events, dialogue, and NPC actions are generated by a stateful agent service.',
    why: 'An AI NPC is more interesting when it changes the world instead of only producing a line of dialogue.',
    built: 'A Unity client that sends world state and applies structured events, plus a Flask/LangGraph backend for lore, decisions, dialogue, and blockchain-aware tools.',
    hardPart: 'Turning probabilistic model output into bounded, structured events the game can actually execute.',
    result: 'A complete game-to-agent loop split cleanly between simulation and reasoning services.',
    repo: 'https://github.com/RealWooblay/minitown-ai-game',
    tech: ['Unity', 'C#', 'Python', 'Flask', 'LangGraph', 'CDP AgentKit'],
    architecture: ['WORLD STATE', 'AGENT SERVICE', 'LORE + EVENT', 'STRUCTURED ACTION', 'UNITY WORLD'],
    accent: '#70d6a6',
  },
  {
    slug: 'ai-action-os',
    title: 'AI Action OS',
    kicker: 'Generative UI · Agents · Approval',
    status: 'Systems prototype',
    description: 'A generative interface where conductor, auditor, and executor agents turn intent into visible, approval-gated actions.',
    why: 'Agent interfaces should expose plans, permissions, and consequences—not hide them behind a typing indicator.',
    built: 'A multi-agent control flow, generated interface layer, approval-gated tools, and an event-sourced SQLite execution ledger.',
    hardPart: 'Keeping generated interaction flexible while preserving a deterministic record of what was proposed, approved, and executed.',
    result: 'A working model for agent software that is inspectable before and after it acts.',
    repo: 'https://github.com/RealWooblay/ai-ui',
    tech: ['TypeScript', 'React', 'SQLite', 'Agent orchestration', 'Tool approval'],
    architecture: ['USER INTENT', 'CONDUCTOR', 'AUDITOR', 'APPROVAL', 'EXECUTOR', 'LEDGER'],
    accent: '#ffda68',
  },
  {
    slug: 'prove-me-wrong',
    title: 'Prove Me Wrong',
    kicker: 'Browser extension · Resolution agents · Solidity',
    status: 'Product prototype',
    description: 'A prediction-market experiment that lets claims emerge from the browser and resolves them through evidence-seeking agents.',
    why: 'Predictions are usually separated from the place the claim was made. This prototype closes that gap and makes evidence collection part of settlement.',
    built: 'A browser overlay, product interface, FastAPI resolution agents, evidence flow, and Solidity settlement contracts.',
    hardPart: 'Representing ambiguous real-world claims precisely enough for both an evidence agent and a contract outcome.',
    result: 'A cross-stack prototype spanning capture, market UX, agent resolution, and settlement.',
    repo: 'https://github.com/RealWooblay/prove-me-wrong',
    tech: ['TypeScript', 'Browser extensions', 'FastAPI', 'Agents', 'Solidity'],
    architecture: ['WEB CLAIM', 'BROWSER OVERLAY', 'MARKET', 'EVIDENCE AGENT', 'SETTLEMENT'],
    accent: '#ff835c',
  },
];

export const projectBySlug = Object.fromEntries(projects.map((project) => [project.slug, project]));
